#docker compose para hambiente de  desarrollo
version: '3.8'

services:

  dock-ang:
    container_name: erp-cont
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:4200'
    